name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - run: yarn constraints
      - run: yarn lint
      - run: yarn workspaces foreach --verbose --topological-dev --parallel --interlaced run build
      - run: yarn test
      - run: yarn semantic-release
        if: github.ref == 'refs/head/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
