name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - run: yarn constraints
      - run: yarn workspaces foreach --verbose --topological-dev --parallel --interlaced run build
      - uses: actions/upload-artifact@v1
        with:
          name: tsconfig-references
          path: packages/tsconfig-references/bundles
